/**
 * Built-in name variant/spelling mapping.
 * Keys are lowercase; values are alternate spellings (title-cased).
 */
const NAME_VARIANTS: Record<string, string[]> = {
  // -- Girls (seed + popular) --
  amara: ['Amira', 'Amora'],
  freya: ['Freja', 'Freyja'],
  nadia: ['Nadya', 'Nadiya'],
  zara: ['Zahra', 'Sara', 'Sarah'],
  cleo: ['Clio'],
  thea: ['Theia', 'Tia'],
  esme: ['Esmé', 'Esmée', 'Esma'],
  mila: ['Milla'],
  bianca: ['Blanca', 'Bianka'],
  daphne: ['Dafne', 'Daphney'],
  hana: ['Hannah', 'Hanna'],
  kaia: ['Kaya', 'Kaiya', 'Kaja'],
  livia: ['Olivia', 'Lyvia'],
  maeve: ['Maev', 'Méabh'],
  nia: ['Nya', 'Niah'],
  selene: ['Selena', 'Celene', 'Celina'],
  talia: ['Thalia', 'Tahlia', 'Talya'],
  zadie: ['Sadie'],
  anika: ['Annika', 'Annica'],
  leilani: ['Lailani', 'Lalani'],

  // Girls — seed names with variants
  aaliyah: ['Aliya', 'Aliyah'],
  audrey: ['Audra'],
  catherine: ['Katherine', 'Kathryn', 'Catharine', 'Katrina'],
  katherine: ['Catherine', 'Kathryn', 'Katharine'],
  sophia: ['Sofia', 'Sofiya'],
  sofia: ['Sophia', 'Sofiya'],
  eleanor: ['Elinor', 'Elanor', 'Eleanore'],
  isabelle: ['Isabel', 'Isobel', 'Isabela'],
  emilia: ['Amelia', 'Emilya'],
  amelia: ['Emilia', 'Amalia'],
  lily: ['Lillie', 'Lili', 'Lilly'],
  madeline: ['Madeleine', 'Madelyn', 'Madilyn'],
  claire: ['Clare', 'Clair'],
  elena: ['Elaina', 'Alena'],
  vivian: ['Vivienne', 'Vivien'],
  natalie: ['Nathalie', 'Natalia'],
  chloe: ['Chloé', 'Khloe'],
  evelyn: ['Evalyn', 'Evelynn'],
  aria: ['Arya', 'Ariya'],
  nora: ['Norah', 'Noura'],
  scarlett: ['Scarlet'],
  violet: ['Violette', 'Violeta'],
  hazel: ['Hazle'],
  aurora: ['Aurore'],
  penelope: ['Penelopy', 'Penélope'],
  layla: ['Leila', 'Leyla', 'Laila'],
  leila: ['Layla', 'Leyla', 'Laila'],
  maya: ['Maia', 'Maja'],
  stella: ['Estella'],
  lucy: ['Lucie', 'Luci'],
  alice: ['Alyce', 'Alyse'],
  grace: ['Gracie'],
  juliet: ['Juliette', 'Julietta'],
  sarah: ['Sara', 'Zara'],
  sara: ['Sarah', 'Zara'],
  hannah: ['Hana', 'Hanna'],
  anna: ['Ana', 'Anya'],
  eva: ['Ava', 'Eve'],
  ava: ['Eva'],
  emma: ['Ema'],
  olivia: ['Livia', 'Alivia'],
  charlotte: ['Charlotta', 'Carlotta'],
  clara: ['Claire', 'Clare', 'Klara'],
  diana: ['Dianna'],
  elizabeth: ['Elisabeth', 'Eliza'],
  eloise: ['Elouise'],
  emily: ['Emilee', 'Emely'],
  fatima: ['Fatimah', 'Fatma'],
  fern: ['Ferne'],
  florence: ['Florrie'],
  frida: ['Frieda'],
  gemma: ['Jemma'],
  harriet: ['Harriett', 'Harriette'],
  helena: ['Helen', 'Helene'],
  imogen: ['Imogene'],
  jade: ['Jada', 'Jayde'],
  jane: ['Jayne'],
  jasmine: ['Jasmin', 'Jazmine', 'Yazmin'],
  kira: ['Keira', 'Kiara', 'Kiera', 'Kyra'],
  lila: ['Lilah', 'Lyla'],
  louisa: ['Louise'],
  lucia: ['Luzia'],
  lydia: ['Lyda'],
  maisie: ['Maisey', 'Maisy', 'Mazie'],
  margaret: ['Margret', 'Margaretta'],
  matilda: ['Mathilda', 'Tilda'],
  miriam: ['Mirjam', 'Miryam'],
  niamh: ['Neve'],
  rosalind: ['Rosaline', 'Rosalyn', 'Roslyn'],
  rose: ['Rosa'],
  sana: ['Sanaa'],
  serena: ['Serina'],
  sienna: ['Siena'],
  soraya: ['Soraia'],
  valentina: ['Valentia'],
  yara: ['Iara'],
  zaina: ['Zayna', 'Zeina'],
  zoe: ['Zoey', 'Zoie'],
  aisling: ['Aislinn', 'Ashling'],
  amira: ['Ameera', 'Amirah'],
  linnea: ['Linnéa'],
  sky: ['Skye'],
  rain: ['Rayne'],

  // -- Boys (seed + popular) --
  jasper: ['Kasper', 'Casper'],
  mateo: ['Matteo', 'Matheo', 'Mattheo'],
  finn: ['Fynn', 'Fin'],
  jules: ['Julian', 'Julius'],
  kiran: ['Kieran', 'Ciaran'],
  luca: ['Luka', 'Lucca'],
  nico: ['Niko', 'Nikko'],
  oscar: ['Oskar'],
  phineas: ['Finneas', 'Phineus'],
  rafael: ['Raphael', 'Raffael'],
  silas: ['Sylas', 'Silus'],
  bastian: ['Sebastian', 'Bastien'],
  emeric: ['Emery', 'Emmerich'],
  lachlan: ['Lochlann', 'Lochlan'],
  nolan: ['Nolen', 'Noland'],

  // Boys — seed names with variants
  alexander: ['Aleksander', 'Alexandre', 'Alexandr'],
  michael: ['Micheal', 'Mikhail', 'Michel'],
  william: ['Willem', 'Liam'],
  liam: ['William', 'Willem'],
  james: ['Jaime', 'Jacques'],
  benjamin: ['Benyamin', 'Benjamín'],
  ethan: ['Eitan', 'Ethen'],
  oliver: ['Olivier', 'Ollie'],
  sebastian: ['Bastian', 'Sébastien'],
  theodore: ['Teodor', 'Théodore'],
  henry: ['Henri', 'Henrik'],
  samuel: ['Samwell', 'Shmuel'],
  daniel: ['Danyal', 'Daniil'],
  jackson: ['Jaxon', 'Jaxson'],
  noah: ['Noa'],
  elijah: ['Elias', 'Eliahu'],
  elias: ['Elijah', 'Elyas'],
  gabriel: ['Gabriël', 'Gabriele'],
  caleb: ['Kaleb', 'Calev'],
  isaac: ['Isaak', 'Ishaq'],
  lucas: ['Lukas', 'Luckas'],
  leo: ['Leon', 'Leonardo'],
  max: ['Maks', 'Maxim'],
  owen: ['Owyn', 'Ewen'],
  jack: ['Jacques', 'Jak'],
  axel: ['Aksel', 'Axl'],
  callum: ['Calum'],
  cosimo: ['Cosmo'],
  forrest: ['Forest'],
  ibrahim: ['Ibraheem'],
  julian: ['Julien'],
  kieran: ['Kieron', 'Kyran'],
  ciaran: ['Ciarán', 'Kieran'],
  lorenzo: ['Enzo', 'Renzo'],
  miles: ['Myles'],
  milo: ['Mylo'],
  nikolai: ['Nikola', 'Nikolay'],
  omar: ['Umar'],
  philip: ['Filip', 'Phillip'],
  rhys: ['Reece', 'Rees'],
  tariq: ['Tarek', 'Tareq', 'Tarik'],
  victor: ['Viktor'],
  wilder: ['Wylder'],
  youssef: ['Yousef', 'Yusuf'],
  zayn: ['Zain'],
  jensen: ['Jenson'],

  // -- Unisex (seed) --
  rowan: ['Rowen', 'Rohan'],
  avery: ['Averie', 'Averi'],
  quinn: ['Quin', 'Quinne'],
  marlowe: ['Marlo', 'Marlow'],
  reese: ['Rhys', 'Reece', 'Rees'],
  sasha: ['Sacha', 'Sascha'],
  wren: ['Ren', 'Wrenn'],
  blair: ['Blaire', 'Blayre'],
  devon: ['Devin', 'Devyn'],
  grey: ['Gray', 'Grae'],
  jordan: ['Jordyn', 'Jordon'],
  remy: ['Remi', 'Rémy'],
  shay: ['Shae', 'Shaye'],

  // Unisex — seed names with variants
  taylor: ['Tayler', 'Tailor'],
  riley: ['Rylee', 'Reilly'],
  casey: ['Kasey', 'Kacey'],
  alex: ['Alix', 'Aleks'],
  charlie: ['Charley', 'Charli'],
  sam: ['Samm'],
  addison: ['Addisyn', 'Addyson'],
  ainsley: ['Ansley'],
  bryn: ['Brynn'],
  cameron: ['Camron', 'Camryn', 'Kameron'],
  emery: ['Emerie', 'Emory'],
  finley: ['Finlay', 'Finnley'],
  jamie: ['Jaime', 'Jaimie'],
  jesse: ['Jessie'],
  marley: ['Marlee', 'Marleigh'],
  noel: ['Noelle'],
  peyton: ['Paityn'],
  skyler: ['Skylar', 'Schuyler'],
}

// De-duplicate variants within each entry
for (const key of Object.keys(NAME_VARIANTS)) {
  NAME_VARIANTS[key] = [...new Set(NAME_VARIANTS[key])]
}

export function getVariants(name: string): string[] {
  return NAME_VARIANTS[name.toLowerCase()] ?? []
}
