-- Seed: ~350 baby names across genders and origins.
-- Name data sourced from behindthename.com (CC BY-SA 4.0),
-- enriched with origin data from Wikipedia and other public sources.
-- couple_id is NULL = global names visible to all couples.

insert into public.names (value, gender, origin, meaning) values
  -- Girls (151)
  ('Aaliyah', 'girl', 'Arabic', 'exalted, sublime'),
  ('Adira', 'girl', 'Hebrew', 'strong, noble'),
  ('Aisling', 'girl', 'Irish', 'dream, vision'),
  ('Alice', 'girl', 'English', 'noble, truthful'),
  ('Amara', 'girl', 'Igbo', 'beloved, grace'),
  ('Amira', 'girl', 'Arabic', 'princess, leader'),
  ('Anika', 'girl', 'Sanskrit', 'grace, favour'),
  ('Anna', 'girl', 'Greek', 'grace, favour'),
  ('Anouk', 'girl', 'French', 'grace'),
  ('Aria', 'girl', 'Italian', 'air, melody'),
  ('Audrey', 'girl', 'English', 'noble strength'),
  ('Aurora', 'girl', 'Latin', 'dawn'),
  ('Autumn', 'girl', 'English', 'fall season'),
  ('Beatrice', 'girl', 'Italian', 'she who brings joy'),
  ('Bianca', 'girl', 'Italian', 'white, shining'),
  ('Briar', 'girl', 'English', 'thorny shrub'),
  ('Caroline', 'girl', 'French', 'free woman'),
  ('Catherine', 'girl', 'French', 'pure'),
  ('Celeste', 'girl', 'Latin', 'heavenly'),
  ('Charlotte', 'girl', 'French', 'free woman'),
  ('Chiara', 'girl', 'Italian', 'bright, clear'),
  ('Chloe', 'girl', 'Greek', 'green shoot'),
  ('Clara', 'girl', 'Latin', 'bright, clear'),
  ('Cleo', 'girl', 'Greek', 'glory, fame'),
  ('Clover', 'girl', 'English', 'clover plant'),
  ('Coral', 'girl', 'English', 'reef, sea growth'),
  ('Dahlia', 'girl', 'Swedish', 'valley flower'),
  ('Daisy', 'girl', 'English', 'day''s eye'),
  ('Daphne', 'girl', 'Greek', 'laurel tree'),
  ('Dawn', 'girl', 'English', 'daybreak'),
  ('Diana', 'girl', 'Latin', 'divine, luminous'),
  ('Elara', 'girl', 'Greek', 'moon of Jupiter'),
  ('Eleanor', 'girl', 'English', 'bright, shining one'),
  ('Elizabeth', 'girl', 'Hebrew', 'pledged to God'),
  ('Elodie', 'girl', 'French', 'foreign riches'),
  ('Eloise', 'girl', 'French', 'healthy, wide'),
  ('Ember', 'girl', 'English', 'glowing fragment'),
  ('Emily', 'girl', 'Latin', 'rival, industrious'),
  ('Emma', 'girl', 'Germanic', 'whole, universal'),
  ('Esme', 'girl', 'French', 'beloved, esteemed'),
  ('Eva', 'girl', 'Hebrew', 'life, living'),
  ('Evelyn', 'girl', 'English', 'wished-for child'),
  ('Fatima', 'girl', 'Arabic', 'splendid one'),
  ('Fern', 'girl', 'English', 'fern plant'),
  ('Flora', 'girl', 'Latin', 'goddess of flowers'),
  ('Florence', 'girl', 'Latin', 'flourishing, prosperous'),
  ('Freya', 'girl', 'Norse', 'noble lady'),
  ('Frida', 'girl', 'Norse', 'peaceful ruler'),
  ('Gemma', 'girl', 'Italian', 'precious stone'),
  ('Genevieve', 'girl', 'French', 'woman of the people'),
  ('Grace', 'girl', 'English', 'grace, elegance'),
  ('Hana', 'girl', 'Japanese', 'flower, blossom'),
  ('Harriet', 'girl', 'English', 'estate ruler'),
  ('Hazel', 'girl', 'English', 'hazelnut tree'),
  ('Helena', 'girl', 'Greek', 'bright light'),
  ('Imogen', 'girl', 'Celtic', 'maiden, girl'),
  ('Inara', 'girl', 'Arabic', 'ray of light'),
  ('Ingrid', 'girl', 'Norse', 'beautiful, beloved'),
  ('Iris', 'girl', 'Greek', 'rainbow'),
  ('Isadora', 'girl', 'Greek', 'gift of Isis'),
  ('Isla', 'girl', 'Scottish', 'island'),
  ('Ivy', 'girl', 'English', 'ivy plant'),
  ('Jade', 'girl', 'English', 'precious green stone'),
  ('Jane', 'girl', 'English', 'God is gracious'),
  ('Jasmine', 'girl', 'Persian', 'fragrant flower'),
  ('Julia', 'girl', 'Latin', 'youthful'),
  ('Juliet', 'girl', 'French', 'youthful, soft'),
  ('Juniper', 'girl', 'English', 'evergreen tree'),
  ('Juno', 'girl', 'Latin', 'queen of the gods'),
  ('Kaia', 'girl', 'Scandinavian', 'earth'),
  ('Katherine', 'girl', 'Greek', 'pure'),
  ('Keiko', 'girl', 'Japanese', 'blessed child'),
  ('Kira', 'girl', 'Russian', 'beam of light'),
  ('Lark', 'girl', 'English', 'songbird'),
  ('Layla', 'girl', 'Arabic', 'night, dark beauty'),
  ('Leila', 'girl', 'Arabic', 'night, dark beauty'),
  ('Leilani', 'girl', 'Hawaiian', 'heavenly garland'),
  ('Lila', 'girl', 'Arabic', 'night, dark beauty'),
  ('Lily', 'girl', 'English', 'lily flower'),
  ('Linnea', 'girl', 'Swedish', 'lime tree'),
  ('Livia', 'girl', 'Latin', 'life, alive'),
  ('Louisa', 'girl', 'French', 'famous warrior'),
  ('Lucia', 'girl', 'Italian', 'light'),
  ('Lucy', 'girl', 'Latin', 'light'),
  ('Luna', 'girl', 'Latin', 'moon'),
  ('Lydia', 'girl', 'Greek', 'from Lydia'),
  ('Maeve', 'girl', 'Irish', 'intoxicating, great'),
  ('Maia', 'girl', 'Greek', 'great mother'),
  ('Maisie', 'girl', 'Scottish', 'pearl'),
  ('Maple', 'girl', 'English', 'maple tree'),
  ('Maren', 'girl', 'Latin', 'of the sea'),
  ('Margaret', 'girl', 'Greek', 'pearl'),
  ('Matilda', 'girl', 'Germanic', 'strength in battle'),
  ('Maya', 'girl', 'Sanskrit', 'illusion, dream'),
  ('Meadow', 'girl', 'English', 'field of grass'),
  ('Mei', 'girl', 'Japanese', 'beautiful, sprout'),
  ('Mila', 'girl', 'Slavic', 'gracious, dear'),
  ('Miriam', 'girl', 'Hebrew', 'wished-for child'),
  ('Nadia', 'girl', 'Slavic', 'hope'),
  ('Naomi', 'girl', 'Hebrew', 'pleasant, beautiful'),
  ('Nia', 'girl', 'Welsh', 'brightness, radiance'),
  ('Niamh', 'girl', 'Irish', 'bright, radiant'),
  ('Noor', 'girl', 'Arabic', 'light, radiance'),
  ('Nora', 'girl', 'Irish', 'honour, light'),
  ('Olive', 'girl', 'English', 'olive tree'),
  ('Olivia', 'girl', 'Latin', 'olive tree'),
  ('Opal', 'girl', 'English', 'precious stone'),
  ('Paloma', 'girl', 'Spanish', 'dove'),
  ('Pearl', 'girl', 'English', 'precious gem'),
  ('Penelope', 'girl', 'Greek', 'weaver'),
  ('Petra', 'girl', 'Greek', 'rock, stone'),
  ('Piper', 'girl', 'English', 'pipe player'),
  ('Poppy', 'girl', 'English', 'red flower'),
  ('Priya', 'girl', 'Sanskrit', 'beloved, darling'),
  ('Rain', 'girl', 'English', 'rainfall'),
  ('Rosalind', 'girl', 'Germanic', 'gentle horse'),
  ('Rose', 'girl', 'English', 'rose flower'),
  ('Ruby', 'girl', 'English', 'red gemstone'),
  ('Rumi', 'girl', 'Japanese', 'beauty, flow'),
  ('Ruth', 'girl', 'Hebrew', 'friend, companion'),
  ('Sadie', 'girl', 'English', 'princess'),
  ('Sakura', 'girl', 'Japanese', 'cherry blossom'),
  ('Sana', 'girl', 'Arabic', 'brilliance, radiance'),
  ('Saoirse', 'girl', 'Irish', 'freedom'),
  ('Scarlett', 'girl', 'English', 'red, scarlet'),
  ('Selene', 'girl', 'Greek', 'moon goddess'),
  ('Serena', 'girl', 'Latin', 'tranquil, serene'),
  ('Sienna', 'girl', 'Italian', 'orange-red, earthy'),
  ('Siri', 'girl', 'Norse', 'beautiful victory'),
  ('Sky', 'girl', 'English', 'sky, heavens'),
  ('Soleil', 'girl', 'French', 'sun'),
  ('Sophia', 'girl', 'Greek', 'wisdom'),
  ('Soraya', 'girl', 'Persian', 'star, princess'),
  ('Stella', 'girl', 'Latin', 'star'),
  ('Talia', 'girl', 'Hebrew', 'gentle dew'),
  ('Thea', 'girl', 'Greek', 'goddess, divine'),
  ('Valentina', 'girl', 'Latin', 'strong, healthy'),
  ('Vera', 'girl', 'Russian', 'truth, faith'),
  ('Violet', 'girl', 'English', 'purple flower'),
  ('Virginia', 'girl', 'Latin', 'pure, maiden'),
  ('Willa', 'girl', 'German', 'resolute protector'),
  ('Willow', 'girl', 'English', 'willow tree'),
  ('Wisteria', 'girl', 'English', 'climbing vine'),
  ('Xanthe', 'girl', 'Greek', 'golden, blonde'),
  ('Yara', 'girl', 'Arabic', 'water lady'),
  ('Yuki', 'girl', 'Japanese', 'snow, happiness'),
  ('Zadie', 'girl', 'English', 'princess'),
  ('Zaina', 'girl', 'Arabic', 'beautiful, radiant'),
  ('Zara', 'girl', 'Arabic', 'blooming, radiant'),
  ('Zelda', 'girl', 'Germanic', 'blessed, happy'),
  ('Zoe', 'girl', 'Greek', 'life'),
  -- Boys (134)
  ('Aarav', 'boy', 'Sanskrit', 'noble one'),
  ('Adam', 'boy', 'Hebrew', 'man, earth'),
  ('Adrian', 'boy', 'Latin', 'from Hadria'),
  ('Akira', 'boy', 'Japanese', 'bright, clear'),
  ('Alexander', 'boy', 'Greek', 'defender of mankind'),
  ('Amari', 'boy', 'African', 'strong, builder'),
  ('Arjun', 'boy', 'Sanskrit', 'bright, shining'),
  ('Arlo', 'boy', 'English', 'fortified hill'),
  ('Arthur', 'boy', 'Celtic', 'bear, noble'),
  ('Ash', 'boy', 'English', 'ash tree'),
  ('Asher', 'boy', 'Hebrew', 'happy, blessed'),
  ('Atlas', 'boy', 'Greek', 'bearer of the heavens'),
  ('Axel', 'boy', 'Scandinavian', 'father of peace'),
  ('Bastian', 'boy', 'Greek', 'revered, venerable'),
  ('Bear', 'boy', 'English', 'strong, brave'),
  ('Beckett', 'boy', 'English', 'bee cottage'),
  ('Benjamin', 'boy', 'Hebrew', 'son of the right hand'),
  ('Bodhi', 'boy', 'Sanskrit', 'awakening, enlightened'),
  ('Brooks', 'boy', 'English', 'of the brook'),
  ('Caleb', 'boy', 'Hebrew', 'faithful, devoted'),
  ('Callum', 'boy', 'Scottish', 'dove'),
  ('Caspian', 'boy', 'Literary', 'of the Caspian Sea'),
  ('Cassian', 'boy', 'Latin', 'hollow, empty'),
  ('Cassius', 'boy', 'Latin', 'hollow, vain'),
  ('Cedar', 'boy', 'English', 'cedar tree'),
  ('Ciaran', 'boy', 'Irish', 'little dark one'),
  ('Cosimo', 'boy', 'Italian', 'order, beauty'),
  ('Daniel', 'boy', 'Hebrew', 'God is my judge'),
  ('Dante', 'boy', 'Italian', 'enduring, steadfast'),
  ('Dashiell', 'boy', 'French', 'from d''Auchy'),
  ('Declan', 'boy', 'Irish', 'full of goodness'),
  ('Edmund', 'boy', 'English', 'wealthy protector'),
  ('Edward', 'boy', 'English', 'wealthy guardian'),
  ('Elijah', 'boy', 'Hebrew', 'my God is Yahweh'),
  ('Elio', 'boy', 'Italian', 'sun'),
  ('Emeric', 'boy', 'German', 'ruler of work'),
  ('Emil', 'boy', 'Latin', 'rival, industrious'),
  ('Emmet', 'boy', 'English', 'industrious, strong'),
  ('Enrique', 'boy', 'Spanish', 'ruler of the home'),
  ('Everett', 'boy', 'English', 'brave, strong boar'),
  ('Ezra', 'boy', 'Hebrew', 'helper, strong'),
  ('Fabian', 'boy', 'Latin', 'bean grower'),
  ('Felix', 'boy', 'Latin', 'happy, fortunate'),
  ('Finn', 'boy', 'Irish', 'fair, white'),
  ('Flint', 'boy', 'English', 'hard stone'),
  ('Florian', 'boy', 'Latin', 'flower, blooming'),
  ('Forrest', 'boy', 'English', 'of the forest'),
  ('Gabriel', 'boy', 'Hebrew', 'God is my strength'),
  ('George', 'boy', 'Greek', 'farmer, earth-worker'),
  ('Gideon', 'boy', 'Hebrew', 'mighty warrior'),
  ('Griffin', 'boy', 'Welsh', 'strong lord'),
  ('Hamza', 'boy', 'Arabic', 'lion, strong'),
  ('Haruki', 'boy', 'Japanese', 'spring, clear'),
  ('Hayes', 'boy', 'English', 'hedged area'),
  ('Heath', 'boy', 'English', 'open land, heathland'),
  ('Hendrix', 'boy', 'English', 'estate ruler'),
  ('Henry', 'boy', 'Germanic', 'ruler of the home'),
  ('Hiro', 'boy', 'Japanese', 'generous, abundant'),
  ('Holden', 'boy', 'English', 'hollow valley'),
  ('Hugo', 'boy', 'German', 'mind, spirit'),
  ('Ibrahim', 'boy', 'Arabic', 'father of nations'),
  ('Idris', 'boy', 'Welsh', 'fiery, ardent'),
  ('Isaac', 'boy', 'Hebrew', 'laughter, joy'),
  ('Isamu', 'boy', 'Japanese', 'brave, courageous'),
  ('Ivo', 'boy', 'German', 'yew tree'),
  ('James', 'boy', 'Hebrew', 'supplanter'),
  ('Jasper', 'boy', 'Persian', 'treasurer'),
  ('Jensen', 'boy', 'Scandinavian', 'son of Jens'),
  ('Joaquin', 'boy', 'Spanish', 'God will establish'),
  ('Jules', 'boy', 'French', 'youthful'),
  ('Julian', 'boy', 'Latin', 'youthful, downy'),
  ('Kabir', 'boy', 'Arabic', 'great, magnificent'),
  ('Kai', 'boy', 'Hawaiian', 'sea, ocean'),
  ('Kieran', 'boy', 'Irish', 'little dark one'),
  ('Kiran', 'boy', 'Sanskrit', 'beam of light'),
  ('Knox', 'boy', 'English', 'round hill'),
  ('Lachlan', 'boy', 'Scottish', 'from the land of lakes'),
  ('Lars', 'boy', 'Scandinavian', 'crowned with laurel'),
  ('Leif', 'boy', 'Norse', 'heir, descendant'),
  ('Leo', 'boy', 'Latin', 'lion'),
  ('Levi', 'boy', 'Hebrew', 'joined, attached'),
  ('Liam', 'boy', 'Irish', 'strong-willed warrior'),
  ('Lorenzo', 'boy', 'Italian', 'from Laurentum'),
  ('Luca', 'boy', 'Italian', 'light'),
  ('Lucas', 'boy', 'Latin', 'light, luminous'),
  ('Magnus', 'boy', 'Latin', 'great, mighty'),
  ('Marco', 'boy', 'Italian', 'dedicated to Mars'),
  ('Mateo', 'boy', 'Spanish', 'gift of God'),
  ('Maxwell', 'boy', 'Scottish', 'great spring'),
  ('Miles', 'boy', 'Latin', 'soldier, merciful'),
  ('Milo', 'boy', 'Germanic', 'soldier, merciful'),
  ('Nico', 'boy', 'Greek', 'victory of the people'),
  ('Nikolai', 'boy', 'Russian', 'victory of the people'),
  ('Noah', 'boy', 'Hebrew', 'rest, comfort'),
  ('Nolan', 'boy', 'Irish', 'noble, famous'),
  ('Oliver', 'boy', 'French', 'olive tree'),
  ('Omar', 'boy', 'Arabic', 'flourishing, long-lived'),
  ('Oren', 'boy', 'Hebrew', 'pine tree, light'),
  ('Orion', 'boy', 'Greek', 'hunter, rising'),
  ('Oscar', 'boy', 'Irish', 'divine spear'),
  ('Otis', 'boy', 'German', 'wealthy, fortunate'),
  ('Owen', 'boy', 'Welsh', 'young warrior, noble'),
  ('Patrick', 'boy', 'Latin', 'noble, patrician'),
  ('Peter', 'boy', 'Greek', 'rock, stone'),
  ('Philip', 'boy', 'Greek', 'lover of horses'),
  ('Phineas', 'boy', 'Hebrew', 'mouth of brass'),
  ('Quincy', 'boy', 'French', 'estate of the fifth'),
  ('Rafael', 'boy', 'Hebrew', 'God has healed'),
  ('Ravi', 'boy', 'Sanskrit', 'sun'),
  ('Reed', 'boy', 'English', 'red-haired'),
  ('Ren', 'boy', 'Japanese', 'lotus, love'),
  ('Rhys', 'boy', 'Welsh', 'ardour, enthusiasm'),
  ('Ronan', 'boy', 'Irish', 'little seal'),
  ('Samuel', 'boy', 'Hebrew', 'God has heard'),
  ('Santiago', 'boy', 'Spanish', 'Saint James'),
  ('Sawyer', 'boy', 'English', 'woodcutter'),
  ('Sebastian', 'boy', 'Greek', 'revered, venerable'),
  ('Silas', 'boy', 'Latin', 'forest, woodland'),
  ('Simon', 'boy', 'Hebrew', 'he has heard'),
  ('Soren', 'boy', 'Danish', 'stern, severe'),
  ('Stellan', 'boy', 'Swedish', 'calm, quiet'),
  ('Stone', 'boy', 'English', 'stone, rock'),
  ('Tariq', 'boy', 'Arabic', 'morning star, visitor'),
  ('Theodore', 'boy', 'Greek', 'gift of God'),
  ('Theron', 'boy', 'Greek', 'hunter, wild beast'),
  ('Thomas', 'boy', 'Aramaic', 'twin'),
  ('Victor', 'boy', 'Latin', 'conqueror, winner'),
  ('Viggo', 'boy', 'Norse', 'war, fight'),
  ('Vincent', 'boy', 'Latin', 'conquering, prevailing'),
  ('Wilder', 'boy', 'English', 'untamed, bold'),
  ('William', 'boy', 'Germanic', 'resolute protector'),
  ('Wolfe', 'boy', 'English', 'wolf'),
  ('Youssef', 'boy', 'Arabic', 'God increases'),
  ('Zayn', 'boy', 'Arabic', 'beauty, grace'),
  -- Unisex (68)
  ('Addison', 'unisex', 'English', 'son of Adam'),
  ('Ainsley', 'unisex', 'English', 'one''s own meadow'),
  ('Alex', 'unisex', 'Greek', 'defender of mankind'),
  ('Arden', 'unisex', 'English', 'high valley'),
  ('Avery', 'unisex', 'English', 'ruler of the elves'),
  ('Bellamy', 'unisex', 'French', 'beautiful friend'),
  ('Blair', 'unisex', 'Scottish', 'field, plain'),
  ('Bryn', 'unisex', 'Welsh', 'hill, mound'),
  ('Cameron', 'unisex', 'Scottish', 'crooked nose'),
  ('Carmen', 'unisex', 'Spanish', 'song, garden'),
  ('Casey', 'unisex', 'Irish', 'watchful, vigilant'),
  ('Charlie', 'unisex', 'English', 'free man'),
  ('Dakota', 'unisex', 'Sioux', 'friend, ally'),
  ('Devon', 'unisex', 'English', 'deep valley'),
  ('Drew', 'unisex', 'English', 'strong, brave'),
  ('Eden', 'unisex', 'Hebrew', 'paradise, delight'),
  ('Ellis', 'unisex', 'Welsh', 'benevolent'),
  ('Emery', 'unisex', 'Germanic', 'industrious ruler'),
  ('Finley', 'unisex', 'Irish', 'fair warrior'),
  ('Frankie', 'unisex', 'English', 'free one'),
  ('Grey', 'unisex', 'English', 'grey-haired'),
  ('Harper', 'unisex', 'English', 'harp player'),
  ('Haven', 'unisex', 'English', 'safe place, refuge'),
  ('Hayden', 'unisex', 'English', 'heather valley'),
  ('Indigo', 'unisex', 'English', 'deep blue dye'),
  ('Jamie', 'unisex', 'English', 'supplanter'),
  ('Jesse', 'unisex', 'Hebrew', 'gift, wealthy'),
  ('Jordan', 'unisex', 'Hebrew', 'to flow down'),
  ('Kendall', 'unisex', 'English', 'royal valley'),
  ('Kit', 'unisex', 'English', 'young cat'),
  ('Lake', 'unisex', 'English', 'body of water'),
  ('Lennox', 'unisex', 'Scottish', 'elm grove'),
  ('Linden', 'unisex', 'English', 'linden tree'),
  ('Loren', 'unisex', 'Latin', 'from Laurentum'),
  ('Marley', 'unisex', 'English', 'pleasant meadow'),
  ('Marlowe', 'unisex', 'English', 'pleasant hill'),
  ('Mica', 'unisex', 'Hebrew', 'who is like God'),
  ('Morgan', 'unisex', 'Welsh', 'sea-born, great'),
  ('Noel', 'unisex', 'French', 'Christmas, birth'),
  ('Nova', 'unisex', 'Latin', 'new, star'),
  ('Oakley', 'unisex', 'English', 'oak meadow'),
  ('Peyton', 'unisex', 'English', 'noble estate'),
  ('Phoenix', 'unisex', 'Greek', 'mythical firebird'),
  ('Quinn', 'unisex', 'Irish', 'counsel, wisdom'),
  ('Rae', 'unisex', 'English', 'grace, doe'),
  ('Reese', 'unisex', 'Welsh', 'ardour, enthusiasm'),
  ('Reign', 'unisex', 'English', 'sovereignty, rule'),
  ('Remy', 'unisex', 'French', 'oarsman, remedy'),
  ('Riley', 'unisex', 'Irish', 'courageous, valiant'),
  ('River', 'unisex', 'English', 'flowing water'),
  ('Robin', 'unisex', 'English', 'bright fame'),
  ('Rooney', 'unisex', 'Irish', 'red-haired'),
  ('Rory', 'unisex', 'Irish', 'red king'),
  ('Rowan', 'unisex', 'Gaelic', 'little red one'),
  ('Sage', 'unisex', 'English', 'wise herb'),
  ('Sam', 'unisex', 'Hebrew', 'heard by God'),
  ('Sasha', 'unisex', 'Russian', 'defender of mankind'),
  ('Shay', 'unisex', 'Irish', 'admirable, hawk-like'),
  ('Skyler', 'unisex', 'English', 'scholar, sheltering'),
  ('Sol', 'unisex', 'Spanish', 'sun'),
  ('Story', 'unisex', 'English', 'tale, narrative'),
  ('Tatum', 'unisex', 'English', 'cheerful, joyful'),
  ('Taylor', 'unisex', 'English', 'cloth cutter'),
  ('Vale', 'unisex', 'Latin', 'valley'),
  ('Vesper', 'unisex', 'Latin', 'evening star'),
  ('Winter', 'unisex', 'English', 'winter season'),
  ('Wren', 'unisex', 'English', 'small songbird'),
  ('Zephyr', 'unisex', 'Greek', 'west wind');
